[package]
name = "bloom-machine-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
triad-dev-harness = ["bloom-triad-local-transport/triad-dev-harness"]

[dependencies]
async-trait.workspace = true
bloom-triad-local-transport.workspace = true
bloom-triad-protocol.workspace = true
fs2.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_jcs.workspace = true
sha2.workspace = true
sha3.workspace = true
tokio = { workspace = true, features = ["net"] }

[dev-dependencies]
ed25519-dalek.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
