[package]
name = "beth"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "bloom-eth daemon and CLI"

[[bin]]
name = "beth"
path = "src/main.rs"

[dependencies]
beth-proto.workspace = true
beth-daemon.workspace = true
beth-keystore.workspace = true
beth-chain.workspace = true
beth-tx.workspace = true
beth-vfs.workspace = true
beth-tools.workspace = true
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
dirs.workspace = true
shellexpand.workspace = true
hex.workspace = true
alloy.workspace = true
base64.workspace = true

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile.workspace = true
